# GCP Settings
app_project = "project-us-350-05"
app_name = "tf-demo-lab"
app_domain = "nttdata.com"
app_environment = "dev"
gcp_region_1  = "europe-west1"
gcp_zone_1    = "europe-west1-b"
gcp_auth_file = "project-us-350-05-c0dfb6cabdcc.json"
 # GCP Network
public_subnet_cidr_1  = "10.10.1.0/24"
